/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author julianm
 */
public class GUIJuegoJ2 extends javax.swing.JPanel {
    int columna = 1;
    Color azul = new Color(51,51,255);
    Color amarillo = new Color(255,255,51);
    Color rojo = new Color(204,0,51);
    Color verde = new Color(0,153,102);
    Color morado = new Color(102,0,102);
    Color cian = new Color(0,204,204);
    Color naranja = new Color(255,153,0);
    Color rosa = new Color(255,204,255);

    /**
     * Creates new form GUIJuegoJ2
     */
    public GUIJuegoJ2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jp1Espiga4 = new javax.swing.JPanel();
        jp1Espiga2 = new javax.swing.JPanel();
        jp1Espiga5 = new javax.swing.JPanel();
        jp2Espiga1 = new javax.swing.JPanel();
        jp2Espiga4 = new javax.swing.JPanel();
        jp2Espiga2 = new javax.swing.JPanel();
        jp2Espiga5 = new javax.swing.JPanel();
        jp3Espiga1 = new javax.swing.JPanel();
        jp3Espiga4 = new javax.swing.JPanel();
        jp3Espiga2 = new javax.swing.JPanel();
        jp3Espiga5 = new javax.swing.JPanel();
        jp4Espiga1 = new javax.swing.JPanel();
        jp4Espiga4 = new javax.swing.JPanel();
        jp4Espiga2 = new javax.swing.JPanel();
        jp4Espiga5 = new javax.swing.JPanel();
        jp5Espiga1 = new javax.swing.JPanel();
        jp5Espiga4 = new javax.swing.JPanel();
        jp5Espiga2 = new javax.swing.JPanel();
        jpf1c1 = new javax.swing.JPanel();
        jp5Espiga5 = new javax.swing.JPanel();
        jpf2c1 = new javax.swing.JPanel();
        jpEscudo2 = new javax.swing.JPanel();
        jpf1c2 = new javax.swing.JPanel();
        jpf1c5 = new javax.swing.JPanel();
        jpf2c3 = new javax.swing.JPanel();
        jpf1c3 = new javax.swing.JPanel();
        jpEscudo4 = new javax.swing.JPanel();
        jpEscudo5 = new javax.swing.JPanel();
        jpEscudo3 = new javax.swing.JPanel();
        jpEscudo1 = new javax.swing.JPanel();
        jpf2c2 = new javax.swing.JPanel();
        jpAmarillo = new javax.swing.JPanel();
        jpf2c4 = new javax.swing.JPanel();
        jpVerde = new javax.swing.JPanel();
        jpf1c4 = new javax.swing.JPanel();
        jpMore = new javax.swing.JPanel();
        jpf2c5 = new javax.swing.JPanel();
        jpRojo = new javax.swing.JPanel();
        jpf3c2 = new javax.swing.JPanel();
        jpAzul = new javax.swing.JPanel();
        jpf3c4 = new javax.swing.JPanel();
        jpCian = new javax.swing.JPanel();
        jpf3c5 = new javax.swing.JPanel();
        jpf3c3 = new javax.swing.JPanel();
        jpf3c1 = new javax.swing.JPanel();
        jpf4c2 = new javax.swing.JPanel();
        jpNaranja = new javax.swing.JPanel();
        jpRosa = new javax.swing.JPanel();
        jp2Espiga3 = new javax.swing.JPanel();
        jp1Espiga3 = new javax.swing.JPanel();
        jpf4c4 = new javax.swing.JPanel();
        jp5Espiga3 = new javax.swing.JPanel();
        jpf4c5 = new javax.swing.JPanel();
        jp3Espiga3 = new javax.swing.JPanel();
        jpf4c3 = new javax.swing.JPanel();
        jp4Espiga3 = new javax.swing.JPanel();
        jpf4c1 = new javax.swing.JPanel();
        jpf5c1 = new javax.swing.JPanel();
        jpf5c2 = new javax.swing.JPanel();
        jpf5c4 = new javax.swing.JPanel();
        jpf5c5 = new javax.swing.JPanel();
        jpf5c3 = new javax.swing.JPanel();
        jp1Espiga1 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jp1Espiga4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp1Espiga4Layout = new javax.swing.GroupLayout(jp1Espiga4);
        jp1Espiga4.setLayout(jp1Espiga4Layout);
        jp1Espiga4Layout.setHorizontalGroup(
            jp1Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp1Espiga4Layout.setVerticalGroup(
            jp1Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jp1Espiga2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp1Espiga2Layout = new javax.swing.GroupLayout(jp1Espiga2);
        jp1Espiga2.setLayout(jp1Espiga2Layout);
        jp1Espiga2Layout.setHorizontalGroup(
            jp1Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp1Espiga2Layout.setVerticalGroup(
            jp1Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jp1Espiga5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp1Espiga5Layout = new javax.swing.GroupLayout(jp1Espiga5);
        jp1Espiga5.setLayout(jp1Espiga5Layout);
        jp1Espiga5Layout.setHorizontalGroup(
            jp1Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jp1Espiga5Layout.setVerticalGroup(
            jp1Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jp2Espiga1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp2Espiga1Layout = new javax.swing.GroupLayout(jp2Espiga1);
        jp2Espiga1.setLayout(jp2Espiga1Layout);
        jp2Espiga1Layout.setHorizontalGroup(
            jp2Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp2Espiga1Layout.setVerticalGroup(
            jp2Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp2Espiga4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp2Espiga4Layout = new javax.swing.GroupLayout(jp2Espiga4);
        jp2Espiga4.setLayout(jp2Espiga4Layout);
        jp2Espiga4Layout.setHorizontalGroup(
            jp2Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp2Espiga4Layout.setVerticalGroup(
            jp2Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp2Espiga2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp2Espiga2Layout = new javax.swing.GroupLayout(jp2Espiga2);
        jp2Espiga2.setLayout(jp2Espiga2Layout);
        jp2Espiga2Layout.setHorizontalGroup(
            jp2Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp2Espiga2Layout.setVerticalGroup(
            jp2Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp2Espiga5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp2Espiga5Layout = new javax.swing.GroupLayout(jp2Espiga5);
        jp2Espiga5.setLayout(jp2Espiga5Layout);
        jp2Espiga5Layout.setHorizontalGroup(
            jp2Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jp2Espiga5Layout.setVerticalGroup(
            jp2Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp3Espiga1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp3Espiga1Layout = new javax.swing.GroupLayout(jp3Espiga1);
        jp3Espiga1.setLayout(jp3Espiga1Layout);
        jp3Espiga1Layout.setHorizontalGroup(
            jp3Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp3Espiga1Layout.setVerticalGroup(
            jp3Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp3Espiga4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp3Espiga4Layout = new javax.swing.GroupLayout(jp3Espiga4);
        jp3Espiga4.setLayout(jp3Espiga4Layout);
        jp3Espiga4Layout.setHorizontalGroup(
            jp3Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp3Espiga4Layout.setVerticalGroup(
            jp3Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jp3Espiga2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp3Espiga2Layout = new javax.swing.GroupLayout(jp3Espiga2);
        jp3Espiga2.setLayout(jp3Espiga2Layout);
        jp3Espiga2Layout.setHorizontalGroup(
            jp3Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp3Espiga2Layout.setVerticalGroup(
            jp3Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp3Espiga5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp3Espiga5Layout = new javax.swing.GroupLayout(jp3Espiga5);
        jp3Espiga5.setLayout(jp3Espiga5Layout);
        jp3Espiga5Layout.setHorizontalGroup(
            jp3Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jp3Espiga5Layout.setVerticalGroup(
            jp3Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jp4Espiga1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp4Espiga1Layout = new javax.swing.GroupLayout(jp4Espiga1);
        jp4Espiga1.setLayout(jp4Espiga1Layout);
        jp4Espiga1Layout.setHorizontalGroup(
            jp4Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp4Espiga1Layout.setVerticalGroup(
            jp4Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp4Espiga4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp4Espiga4Layout = new javax.swing.GroupLayout(jp4Espiga4);
        jp4Espiga4.setLayout(jp4Espiga4Layout);
        jp4Espiga4Layout.setHorizontalGroup(
            jp4Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp4Espiga4Layout.setVerticalGroup(
            jp4Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jp4Espiga2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp4Espiga2Layout = new javax.swing.GroupLayout(jp4Espiga2);
        jp4Espiga2.setLayout(jp4Espiga2Layout);
        jp4Espiga2Layout.setHorizontalGroup(
            jp4Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp4Espiga2Layout.setVerticalGroup(
            jp4Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp4Espiga5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp4Espiga5Layout = new javax.swing.GroupLayout(jp4Espiga5);
        jp4Espiga5.setLayout(jp4Espiga5Layout);
        jp4Espiga5Layout.setHorizontalGroup(
            jp4Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jp4Espiga5Layout.setVerticalGroup(
            jp4Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jp5Espiga1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp5Espiga1Layout = new javax.swing.GroupLayout(jp5Espiga1);
        jp5Espiga1.setLayout(jp5Espiga1Layout);
        jp5Espiga1Layout.setHorizontalGroup(
            jp5Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp5Espiga1Layout.setVerticalGroup(
            jp5Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp5Espiga4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp5Espiga4Layout = new javax.swing.GroupLayout(jp5Espiga4);
        jp5Espiga4.setLayout(jp5Espiga4Layout);
        jp5Espiga4Layout.setHorizontalGroup(
            jp5Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp5Espiga4Layout.setVerticalGroup(
            jp5Espiga4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jp5Espiga2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp5Espiga2Layout = new javax.swing.GroupLayout(jp5Espiga2);
        jp5Espiga2.setLayout(jp5Espiga2Layout);
        jp5Espiga2Layout.setHorizontalGroup(
            jp5Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp5Espiga2Layout.setVerticalGroup(
            jp5Espiga2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jpf1c1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf1c1Layout = new javax.swing.GroupLayout(jpf1c1);
        jpf1c1.setLayout(jpf1c1Layout);
        jpf1c1Layout.setHorizontalGroup(
            jpf1c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf1c1Layout.setVerticalGroup(
            jpf1c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jp5Espiga5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp5Espiga5Layout = new javax.swing.GroupLayout(jp5Espiga5);
        jp5Espiga5.setLayout(jp5Espiga5Layout);
        jp5Espiga5Layout.setHorizontalGroup(
            jp5Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        jp5Espiga5Layout.setVerticalGroup(
            jp5Espiga5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jpf2c1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf2c1Layout = new javax.swing.GroupLayout(jpf2c1);
        jpf2c1.setLayout(jpf2c1Layout);
        jpf2c1Layout.setHorizontalGroup(
            jpf2c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf2c1Layout.setVerticalGroup(
            jpf2c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpEscudo2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpEscudo2Layout = new javax.swing.GroupLayout(jpEscudo2);
        jpEscudo2.setLayout(jpEscudo2Layout);
        jpEscudo2Layout.setHorizontalGroup(
            jpEscudo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpEscudo2Layout.setVerticalGroup(
            jpEscudo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf1c2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf1c2Layout = new javax.swing.GroupLayout(jpf1c2);
        jpf1c2.setLayout(jpf1c2Layout);
        jpf1c2Layout.setHorizontalGroup(
            jpf1c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf1c2Layout.setVerticalGroup(
            jpf1c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf1c5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf1c5Layout = new javax.swing.GroupLayout(jpf1c5);
        jpf1c5.setLayout(jpf1c5Layout);
        jpf1c5Layout.setHorizontalGroup(
            jpf1c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf1c5Layout.setVerticalGroup(
            jpf1c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf2c3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf2c3Layout = new javax.swing.GroupLayout(jpf2c3);
        jpf2c3.setLayout(jpf2c3Layout);
        jpf2c3Layout.setHorizontalGroup(
            jpf2c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf2c3Layout.setVerticalGroup(
            jpf2c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf1c3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf1c3Layout = new javax.swing.GroupLayout(jpf1c3);
        jpf1c3.setLayout(jpf1c3Layout);
        jpf1c3Layout.setHorizontalGroup(
            jpf1c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf1c3Layout.setVerticalGroup(
            jpf1c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpEscudo4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpEscudo4Layout = new javax.swing.GroupLayout(jpEscudo4);
        jpEscudo4.setLayout(jpEscudo4Layout);
        jpEscudo4Layout.setHorizontalGroup(
            jpEscudo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpEscudo4Layout.setVerticalGroup(
            jpEscudo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpEscudo5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpEscudo5Layout = new javax.swing.GroupLayout(jpEscudo5);
        jpEscudo5.setLayout(jpEscudo5Layout);
        jpEscudo5Layout.setHorizontalGroup(
            jpEscudo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpEscudo5Layout.setVerticalGroup(
            jpEscudo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpEscudo3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpEscudo3Layout = new javax.swing.GroupLayout(jpEscudo3);
        jpEscudo3.setLayout(jpEscudo3Layout);
        jpEscudo3Layout.setHorizontalGroup(
            jpEscudo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpEscudo3Layout.setVerticalGroup(
            jpEscudo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpEscudo1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpEscudo1Layout = new javax.swing.GroupLayout(jpEscudo1);
        jpEscudo1.setLayout(jpEscudo1Layout);
        jpEscudo1Layout.setHorizontalGroup(
            jpEscudo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpEscudo1Layout.setVerticalGroup(
            jpEscudo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf2c2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf2c2Layout = new javax.swing.GroupLayout(jpf2c2);
        jpf2c2.setLayout(jpf2c2Layout);
        jpf2c2Layout.setHorizontalGroup(
            jpf2c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf2c2Layout.setVerticalGroup(
            jpf2c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpAmarillo.setBackground(new java.awt.Color(255, 255, 51));
        jpAmarillo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAmarilloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpAmarilloLayout = new javax.swing.GroupLayout(jpAmarillo);
        jpAmarillo.setLayout(jpAmarilloLayout);
        jpAmarilloLayout.setHorizontalGroup(
            jpAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpAmarilloLayout.setVerticalGroup(
            jpAmarilloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpf2c4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf2c4Layout = new javax.swing.GroupLayout(jpf2c4);
        jpf2c4.setLayout(jpf2c4Layout);
        jpf2c4Layout.setHorizontalGroup(
            jpf2c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf2c4Layout.setVerticalGroup(
            jpf2c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpVerde.setBackground(new java.awt.Color(0, 153, 102));
        jpVerde.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpVerdeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpVerdeLayout = new javax.swing.GroupLayout(jpVerde);
        jpVerde.setLayout(jpVerdeLayout);
        jpVerdeLayout.setHorizontalGroup(
            jpVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpVerdeLayout.setVerticalGroup(
            jpVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpf1c4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf1c4Layout = new javax.swing.GroupLayout(jpf1c4);
        jpf1c4.setLayout(jpf1c4Layout);
        jpf1c4Layout.setHorizontalGroup(
            jpf1c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf1c4Layout.setVerticalGroup(
            jpf1c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpMore.setBackground(new java.awt.Color(102, 0, 102));
        jpMore.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpMore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpMoreMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpMoreLayout = new javax.swing.GroupLayout(jpMore);
        jpMore.setLayout(jpMoreLayout);
        jpMoreLayout.setHorizontalGroup(
            jpMoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        jpMoreLayout.setVerticalGroup(
            jpMoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpf2c5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf2c5Layout = new javax.swing.GroupLayout(jpf2c5);
        jpf2c5.setLayout(jpf2c5Layout);
        jpf2c5Layout.setHorizontalGroup(
            jpf2c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf2c5Layout.setVerticalGroup(
            jpf2c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpRojo.setBackground(new java.awt.Color(204, 0, 51));
        jpRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpRojoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpRojoLayout = new javax.swing.GroupLayout(jpRojo);
        jpRojo.setLayout(jpRojoLayout);
        jpRojoLayout.setHorizontalGroup(
            jpRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpRojoLayout.setVerticalGroup(
            jpRojoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpf3c2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf3c2Layout = new javax.swing.GroupLayout(jpf3c2);
        jpf3c2.setLayout(jpf3c2Layout);
        jpf3c2Layout.setHorizontalGroup(
            jpf3c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf3c2Layout.setVerticalGroup(
            jpf3c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jpAzul.setBackground(new java.awt.Color(51, 51, 255));
        jpAzul.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpAzulMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpAzulLayout = new javax.swing.GroupLayout(jpAzul);
        jpAzul.setLayout(jpAzulLayout);
        jpAzulLayout.setHorizontalGroup(
            jpAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpAzulLayout.setVerticalGroup(
            jpAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jpf3c4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf3c4Layout = new javax.swing.GroupLayout(jpf3c4);
        jpf3c4.setLayout(jpf3c4Layout);
        jpf3c4Layout.setHorizontalGroup(
            jpf3c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf3c4Layout.setVerticalGroup(
            jpf3c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jpCian.setBackground(new java.awt.Color(0, 204, 204));
        jpCian.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpCian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpCianMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpCianLayout = new javax.swing.GroupLayout(jpCian);
        jpCian.setLayout(jpCianLayout);
        jpCianLayout.setHorizontalGroup(
            jpCianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        jpCianLayout.setVerticalGroup(
            jpCianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpf3c5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf3c5Layout = new javax.swing.GroupLayout(jpf3c5);
        jpf3c5.setLayout(jpf3c5Layout);
        jpf3c5Layout.setHorizontalGroup(
            jpf3c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf3c5Layout.setVerticalGroup(
            jpf3c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jpf3c3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf3c3Layout = new javax.swing.GroupLayout(jpf3c3);
        jpf3c3.setLayout(jpf3c3Layout);
        jpf3c3Layout.setHorizontalGroup(
            jpf3c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf3c3Layout.setVerticalGroup(
            jpf3c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jpf3c1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf3c1Layout = new javax.swing.GroupLayout(jpf3c1);
        jpf3c1.setLayout(jpf3c1Layout);
        jpf3c1Layout.setHorizontalGroup(
            jpf3c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf3c1Layout.setVerticalGroup(
            jpf3c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jpf4c2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf4c2Layout = new javax.swing.GroupLayout(jpf4c2);
        jpf4c2.setLayout(jpf4c2Layout);
        jpf4c2Layout.setHorizontalGroup(
            jpf4c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf4c2Layout.setVerticalGroup(
            jpf4c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpNaranja.setBackground(new java.awt.Color(255, 153, 0));
        jpNaranja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpNaranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpNaranjaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpNaranjaLayout = new javax.swing.GroupLayout(jpNaranja);
        jpNaranja.setLayout(jpNaranjaLayout);
        jpNaranjaLayout.setHorizontalGroup(
            jpNaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jpNaranjaLayout.setVerticalGroup(
            jpNaranjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jpRosa.setBackground(new java.awt.Color(255, 204, 255));
        jpRosa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpRosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpRosaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpRosaLayout = new javax.swing.GroupLayout(jpRosa);
        jpRosa.setLayout(jpRosaLayout);
        jpRosaLayout.setHorizontalGroup(
            jpRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpRosaLayout.setVerticalGroup(
            jpRosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jp2Espiga3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp2Espiga3Layout = new javax.swing.GroupLayout(jp2Espiga3);
        jp2Espiga3.setLayout(jp2Espiga3Layout);
        jp2Espiga3Layout.setHorizontalGroup(
            jp2Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp2Espiga3Layout.setVerticalGroup(
            jp2Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jp1Espiga3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp1Espiga3Layout = new javax.swing.GroupLayout(jp1Espiga3);
        jp1Espiga3.setLayout(jp1Espiga3Layout);
        jp1Espiga3Layout.setHorizontalGroup(
            jp1Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp1Espiga3Layout.setVerticalGroup(
            jp1Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jpf4c4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf4c4Layout = new javax.swing.GroupLayout(jpf4c4);
        jpf4c4.setLayout(jpf4c4Layout);
        jpf4c4Layout.setHorizontalGroup(
            jpf4c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf4c4Layout.setVerticalGroup(
            jpf4c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jp5Espiga3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp5Espiga3Layout = new javax.swing.GroupLayout(jp5Espiga3);
        jp5Espiga3.setLayout(jp5Espiga3Layout);
        jp5Espiga3Layout.setHorizontalGroup(
            jp5Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp5Espiga3Layout.setVerticalGroup(
            jp5Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jpf4c5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf4c5Layout = new javax.swing.GroupLayout(jpf4c5);
        jpf4c5.setLayout(jpf4c5Layout);
        jpf4c5Layout.setHorizontalGroup(
            jpf4c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf4c5Layout.setVerticalGroup(
            jpf4c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jp3Espiga3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp3Espiga3Layout = new javax.swing.GroupLayout(jp3Espiga3);
        jp3Espiga3.setLayout(jp3Espiga3Layout);
        jp3Espiga3Layout.setHorizontalGroup(
            jp3Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp3Espiga3Layout.setVerticalGroup(
            jp3Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jpf4c3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf4c3Layout = new javax.swing.GroupLayout(jpf4c3);
        jpf4c3.setLayout(jpf4c3Layout);
        jpf4c3Layout.setHorizontalGroup(
            jpf4c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf4c3Layout.setVerticalGroup(
            jpf4c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jp4Espiga3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp4Espiga3Layout = new javax.swing.GroupLayout(jp4Espiga3);
        jp4Espiga3.setLayout(jp4Espiga3Layout);
        jp4Espiga3Layout.setHorizontalGroup(
            jp4Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp4Espiga3Layout.setVerticalGroup(
            jp4Espiga3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jpf4c1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf4c1Layout = new javax.swing.GroupLayout(jpf4c1);
        jpf4c1.setLayout(jpf4c1Layout);
        jpf4c1Layout.setHorizontalGroup(
            jpf4c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf4c1Layout.setVerticalGroup(
            jpf4c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf5c1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf5c1Layout = new javax.swing.GroupLayout(jpf5c1);
        jpf5c1.setLayout(jpf5c1Layout);
        jpf5c1Layout.setHorizontalGroup(
            jpf5c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf5c1Layout.setVerticalGroup(
            jpf5c1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf5c2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf5c2Layout = new javax.swing.GroupLayout(jpf5c2);
        jpf5c2.setLayout(jpf5c2Layout);
        jpf5c2Layout.setHorizontalGroup(
            jpf5c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf5c2Layout.setVerticalGroup(
            jpf5c2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf5c4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf5c4Layout = new javax.swing.GroupLayout(jpf5c4);
        jpf5c4.setLayout(jpf5c4Layout);
        jpf5c4Layout.setHorizontalGroup(
            jpf5c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf5c4Layout.setVerticalGroup(
            jpf5c4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf5c5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf5c5Layout = new javax.swing.GroupLayout(jpf5c5);
        jpf5c5.setLayout(jpf5c5Layout);
        jpf5c5Layout.setHorizontalGroup(
            jpf5c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf5c5Layout.setVerticalGroup(
            jpf5c5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jpf5c3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpf5c3Layout = new javax.swing.GroupLayout(jpf5c3);
        jpf5c3.setLayout(jpf5c3Layout);
        jpf5c3Layout.setHorizontalGroup(
            jpf5c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );
        jpf5c3Layout.setVerticalGroup(
            jpf5c3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jp1Espiga1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp1Espiga1Layout = new javax.swing.GroupLayout(jp1Espiga1);
        jp1Espiga1.setLayout(jp1Espiga1Layout);
        jp1Espiga1Layout.setHorizontalGroup(
            jp1Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jp1Espiga1Layout.setVerticalGroup(
            jp1Espiga1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jpf5c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpf5c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpf5c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jpf5c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpf5c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jpf4c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jpf4c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jpf4c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jpf4c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jpf4c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jpf3c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jpf3c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jpf3c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)
                                            .addComponent(jpf3c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jpf1c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jpf2c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jpf1c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jpf1c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(jpf1c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jpf2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jpf2c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jpf2c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jpf2c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jpf1c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jpf3c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jp3Espiga4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jp3Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jp3Espiga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jp3Espiga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jp3Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jp4Espiga4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jp4Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jp4Espiga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jp4Espiga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jp4Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jp5Espiga4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jp5Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jp5Espiga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jp5Espiga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jp5Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jp2Espiga4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jp2Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jp2Espiga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jp2Espiga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jp2Espiga3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jp1Espiga4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jp1Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jp1Espiga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jp1Espiga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jp1Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jpAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jpEscudo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpEscudo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpEscudo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jpEscudo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpEscudo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jpAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpMore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpCian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpRosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp1Espiga1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp1Espiga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp1Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp1Espiga4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp1Espiga5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jpf1c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpf1c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpf1c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpf1c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpf1c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp2Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp2Espiga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp2Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp2Espiga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp2Espiga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jpf2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpf2c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpf2c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpf2c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpf2c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jp3Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp3Espiga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jp3Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jp3Espiga5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp3Espiga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpf3c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf3c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf3c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf3c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf3c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jp4Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jp4Espiga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jp4Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jp4Espiga5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jp4Espiga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jpf4c5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpf5c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jp5Espiga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jp5Espiga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jp5Espiga3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jp5Espiga5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jp5Espiga4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpf4c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf4c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf4c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf4c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpf5c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf5c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf5c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf5c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEscudo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEscudo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEscudo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEscudo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpEscudo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpCian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpMore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpVerde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpRojo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpAmarillo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpAzul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jpRosa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpNaranja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jpRosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpRosaMouseClicked
        if (columna == 6) {
            System.err.println("Error: Ya se enviaron los colores");
        }else{
            switch (columna) {
             case 1 -> {this.jpf1c1.setBackground(rosa); columna++;}
             case 2 -> {this.jpf1c2.setBackground(rosa); columna++;}
             case 3 -> {this.jpf1c3.setBackground(rosa); columna++;}
             case 4 -> {this.jpf1c4.setBackground(rosa); columna++;}
             case 5 -> {this.jpf1c5.setBackground(rosa); columna++;}
             default -> throw new AssertionError();
            }
        }
    }//GEN-LAST:event_jpRosaMouseClicked

    private void jpNaranjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpNaranjaMouseClicked
        if (columna == 6) {
            System.err.println("Error: Ya se enviaron los colores");
        }else{
            switch (columna) {
             case 1 -> {this.jpf1c1.setBackground(naranja); columna++;}
             case 2 -> {this.jpf1c2.setBackground(naranja); columna++;}
             case 3 -> {this.jpf1c3.setBackground(naranja); columna++;}
             case 4 -> {this.jpf1c4.setBackground(naranja); columna++;}
             case 5 -> {this.jpf1c5.setBackground(naranja); columna++;}
             default -> throw new AssertionError();
            }
        }
    
    }//GEN-LAST:event_jpNaranjaMouseClicked

    private void jpCianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCianMouseClicked
        if (columna == 6) {
            System.err.println("Error: Ya se enviaron los colores");
        }else{
            switch (columna) {
             case 1 -> {this.jpf1c1.setBackground(cian); columna++;}
             case 2 -> {this.jpf1c2.setBackground(cian); columna++;}
             case 3 -> {this.jpf1c3.setBackground(cian); columna++;}
             case 4 -> {this.jpf1c4.setBackground(cian); columna++;}
             case 5 -> {this.jpf1c5.setBackground(cian); columna++;}
             default -> throw new AssertionError();
            }
        }      
    }//GEN-LAST:event_jpCianMouseClicked

    private void jpAzulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAzulMouseClicked
        if (columna == 6) {
            System.err.println("Error: Ya se enviaron los colores");
        }else{
            switch (columna) {
             case 1 -> {this.jpf1c1.setBackground(azul); columna++;}
             case 2 -> {this.jpf1c2.setBackground(azul); columna++;}
             case 3 -> {this.jpf1c3.setBackground(azul); columna++;}
             case 4 -> {this.jpf1c4.setBackground(azul); columna++;}
             case 5 -> {this.jpf1c5.setBackground(azul); columna++;}
             default -> throw new AssertionError();
            }
        }       
    }//GEN-LAST:event_jpAzulMouseClicked

    private void jpRojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpRojoMouseClicked
        if (columna == 6) {
            System.err.println("Eror: Ya se enviaron los colores");
        }else{
            switch (columna) {
             case 1 -> {this.jpf1c1.setBackground(rojo); columna++;}
             case 2 -> {this.jpf1c2.setBackground(rojo); columna++;}
             case 3 -> {this.jpf1c3.setBackground(rojo); columna++;}
             case 4 -> {this.jpf1c4.setBackground(rojo); columna++;}
             case 5 -> {this.jpf1c5.setBackground(rojo); columna++;}
             default -> throw new AssertionError();
            }
        }       
    }//GEN-LAST:event_jpRojoMouseClicked

    private void jpMoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMoreMouseClicked
        if (columna == 6) {
            System.err.println("Error: Ya se enviaron los colores");
        }else{
            switch (columna) {
             case 1 -> {this.jpf1c1.setBackground(morado); columna++;}
             case 2 -> {this.jpf1c2.setBackground(morado); columna++;}
             case 3 -> {this.jpf1c3.setBackground(morado); columna++;}
             case 4 -> {this.jpf1c4.setBackground(morado); columna++;}
             case 5 -> {this.jpf1c5.setBackground(morado); columna++;}
             default -> throw new AssertionError();
            }
        }       
    }//GEN-LAST:event_jpMoreMouseClicked

    private void jpVerdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVerdeMouseClicked
        if (columna == 6) {
            System.err.println("Error: Ya se enviaron los colores");
        }else{
            switch (columna) {
             case 1 -> {this.jpf1c1.setBackground(verde); columna++;}
             case 2 -> {this.jpf1c2.setBackground(verde); columna++;}
             case 3 -> {this.jpf1c3.setBackground(verde); columna++;}
             case 4 -> {this.jpf1c4.setBackground(verde); columna++;}
             case 5 -> {this.jpf1c5.setBackground(verde); columna++;}
             default -> throw new AssertionError();
            }
        }       
    }//GEN-LAST:event_jpVerdeMouseClicked

    private void jpAmarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpAmarilloMouseClicked
        if (columna == 6) {
            System.err.println("Error: Ya se enviaron los colores");
        }else{
            switch (columna) {
             case 1 -> {this.jpf1c1.setBackground(amarillo); columna++;}
             case 2 -> {this.jpf1c2.setBackground(amarillo); columna++;}
             case 3 -> {this.jpf1c3.setBackground(amarillo); columna++;}
             case 4 -> {this.jpf1c4.setBackground(amarillo); columna++;}
             case 5 -> {this.jpf1c5.setBackground(amarillo); columna++;}
             default -> throw new AssertionError();
            }
        }       
    }//GEN-LAST:event_jpAmarilloMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp1Espiga1;
    private javax.swing.JPanel jp1Espiga2;
    private javax.swing.JPanel jp1Espiga3;
    private javax.swing.JPanel jp1Espiga4;
    private javax.swing.JPanel jp1Espiga5;
    private javax.swing.JPanel jp2Espiga1;
    private javax.swing.JPanel jp2Espiga2;
    private javax.swing.JPanel jp2Espiga3;
    private javax.swing.JPanel jp2Espiga4;
    private javax.swing.JPanel jp2Espiga5;
    private javax.swing.JPanel jp3Espiga1;
    private javax.swing.JPanel jp3Espiga2;
    private javax.swing.JPanel jp3Espiga3;
    private javax.swing.JPanel jp3Espiga4;
    private javax.swing.JPanel jp3Espiga5;
    private javax.swing.JPanel jp4Espiga1;
    private javax.swing.JPanel jp4Espiga2;
    private javax.swing.JPanel jp4Espiga3;
    private javax.swing.JPanel jp4Espiga4;
    private javax.swing.JPanel jp4Espiga5;
    private javax.swing.JPanel jp5Espiga1;
    private javax.swing.JPanel jp5Espiga2;
    private javax.swing.JPanel jp5Espiga3;
    private javax.swing.JPanel jp5Espiga4;
    private javax.swing.JPanel jp5Espiga5;
    private javax.swing.JPanel jpAmarillo;
    private javax.swing.JPanel jpAzul;
    private javax.swing.JPanel jpCian;
    private javax.swing.JPanel jpEscudo1;
    private javax.swing.JPanel jpEscudo2;
    private javax.swing.JPanel jpEscudo3;
    private javax.swing.JPanel jpEscudo4;
    private javax.swing.JPanel jpEscudo5;
    private javax.swing.JPanel jpMore;
    private javax.swing.JPanel jpNaranja;
    private javax.swing.JPanel jpRojo;
    private javax.swing.JPanel jpRosa;
    private javax.swing.JPanel jpVerde;
    private javax.swing.JPanel jpf1c1;
    private javax.swing.JPanel jpf1c2;
    private javax.swing.JPanel jpf1c3;
    private javax.swing.JPanel jpf1c4;
    private javax.swing.JPanel jpf1c5;
    private javax.swing.JPanel jpf2c1;
    private javax.swing.JPanel jpf2c2;
    private javax.swing.JPanel jpf2c3;
    private javax.swing.JPanel jpf2c4;
    private javax.swing.JPanel jpf2c5;
    private javax.swing.JPanel jpf3c1;
    private javax.swing.JPanel jpf3c2;
    private javax.swing.JPanel jpf3c3;
    private javax.swing.JPanel jpf3c4;
    private javax.swing.JPanel jpf3c5;
    private javax.swing.JPanel jpf4c1;
    private javax.swing.JPanel jpf4c2;
    private javax.swing.JPanel jpf4c3;
    private javax.swing.JPanel jpf4c4;
    private javax.swing.JPanel jpf4c5;
    private javax.swing.JPanel jpf5c1;
    private javax.swing.JPanel jpf5c2;
    private javax.swing.JPanel jpf5c3;
    private javax.swing.JPanel jpf5c4;
    private javax.swing.JPanel jpf5c5;
    // End of variables declaration//GEN-END:variables
}
